# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Uniqueness of CRPs
#'
#' The uniqueness is calculated as the average of the hamming distance of the CRPs of two devices, for every pair of devices.
#' The number of pairs of devices is calculated with the following formula, where \eqn{D} is the number of devices.
#' \deqn{N = \frac{D(D-1)}{2}}
#'
#' @param crps A logical or numeric matrix
#'
#' @return The uniqueness of the CRP table
#'
#' @export
#' @examples
#' mat <- rbits(c(10, 10))
#' uniqueness(mat)
uniqueness <- function(crps) {
    .Call(`_pufr_uniqueness`, crps)
}

